apiVersion: v1
kind: Pod

metadata:
  name: safe-pod

spec:
  containers:
    - name: nginx
      image: nginx:1.25ok

      imagePullPolicy: IfNotPresent

      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true

      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"